-- DB분석용
--일자별(ADDDATE) 출고정보 연동 건수 집계
SELECT * from openquery(CJ_3PL, '
	select *
	from P1_V_ORDERS
	where ADDDATE LIKE ''20240828%''
')

SELECT * from openquery(CJ_3PL, '
	select substr(ADDDATE, 1, 8) as date_only, COUNT(*) as row_count 
	from P1_V_ORDERS
	group by date_only
')

SELECT * from openquery(CJ_3PL, '
	select substr(ADDDATE, 1, 8) as DATE_ONLY, count(*) as ROW_COUNT
	from P1_V_ORDERS
	group by substr(ADDDATE, 1, 8)
	order by substr(ADDDATE, 1, 8)
')

SELECT * from openquery(CJ_3PL, '
	select *
	from P1_V_ORDERS T1
	WHERE T1.ORDERDATE LIKE ''20241006%''
')

SELECT * from openquery(CJ_3PL, '
	select *
	from
		(SELECT ORDERDATE AS ORDER1, COUNT(*) AS COUNT1
		FROM P1_V_ORDERS
		GROUP BY ORDERDATE) T1
	FULL OUTER JOIN
		(SELECT ORDERDATE AS ORDER2, COUNT(*) AS COUNT2
		FROM P1_V_ORDERS_TO
		GROUP BY ORDERDATE) T2
	ON T1.ORDER1 = T2.ORDER2
')
---완성!
SELECT * from openquery(CJ_3PL, '
	select *
	from
		(SELECT SUBSTR(ADDDATE, 1, 8) AS T1_ADDDATE, 
				COUNT(*) AS T1_TOTAL, 
				SUM(CASE WHEN TRANSSTATE = ''Y'' THEN 1 ELSE 0 END) AS TRANS1_Y,
				SUM(CASE WHEN TRANSSTATE = ''N'' THEN 1 ELSE 0 END) AS TRANS1_N,
				SUM(CASE WHEN TRANSSTATE = ''D'' THEN 1 ELSE 0 END) AS TRANS1_D,
				SUM(CASE WHEN TRANSSTATE = ''E'' THEN 1 ELSE 0 END) AS TRANS1_E,
				SUM(CASE WHEN RSLTSTATE = ''Y'' THEN 1 ELSE 0 END) AS RSLT1_Y,
				SUM(CASE WHEN RSLTSTATE = ''N'' THEN 1 ELSE 0 END) AS RSLT1_N,
				SUM(CASE WHEN RSLTSTATE = ''D'' THEN 1 ELSE 0 END) AS RSLT1_D,
				SUM(CASE WHEN RSLTSTATE = ''E'' THEN 1 ELSE 0 END) AS RSLT1_E,
				SUM(CASE WHEN READSTATE = ''Y'' THEN 1 ELSE 0 END) AS READ1_Y,
				SUM(CASE WHEN READSTATE = ''N'' THEN 1 ELSE 0 END) AS READ1_N,
				SUM(CASE WHEN READSTATE = ''D'' THEN 1 ELSE 0 END) AS READ1_D,
				SUM(CASE WHEN READSTATE = ''E'' THEN 1 ELSE 0 END) AS READ1_E
		FROM P1_V_ORDERS
		GROUP BY SUBSTR(ADDDATE, 1, 8)) T1
	FULL OUTER JOIN
		(SELECT SUBSTR(ADDDATE, 1, 8) AS T2_ADDDATE, 
				COUNT(*) AS T2_TOTAL,
				SUM(CASE WHEN TRANSSTATE = ''Y'' THEN 1 ELSE 0 END) AS TRANS2_Y,
				SUM(CASE WHEN TRANSSTATE = ''N'' THEN 1 ELSE 0 END) AS TRANS2_N,
				SUM(CASE WHEN TRANSSTATE = ''D'' THEN 1 ELSE 0 END) AS TRANS2_D,
				SUM(CASE WHEN TRANSSTATE = ''E'' THEN 1 ELSE 0 END) AS TRANS2_E,
				SUM(CASE WHEN RSLTSTATE = ''Y'' THEN 1 ELSE 0 END) AS RSLT2_Y,
				SUM(CASE WHEN RSLTSTATE = ''N'' THEN 1 ELSE 0 END) AS RSLT2_N,
				SUM(CASE WHEN RSLTSTATE = ''D'' THEN 1 ELSE 0 END) AS RSLT2_D,
				SUM(CASE WHEN RSLTSTATE = ''E'' THEN 1 ELSE 0 END) AS RSLT2_E,
				SUM(CASE WHEN READSTATE = ''Y'' THEN 1 ELSE 0 END) AS READ2_Y,
				SUM(CASE WHEN READSTATE = ''N'' THEN 1 ELSE 0 END) AS READ2_N,
				SUM(CASE WHEN READSTATE = ''D'' THEN 1 ELSE 0 END) AS READ2_D,
				SUM(CASE WHEN READSTATE = ''E'' THEN 1 ELSE 0 END) AS READ2_E
		FROM P1_V_ORDERS_TO
		GROUP BY SUBSTR(ADDDATE, 1, 8)) T2
	ON T1.T1_ADDDATE = T2.T2_ADDDATE
	ORDER BY T1.T1_ADDDATE
')

SELECT * from openquery(CJ_3PL, 'SELECT * FROM P1_V_ORDERS WHERE READSTATE = ''E'' AND RSLTSTATE = ''Y''')



---완성2!
SELECT * from openquery(CJ_3PL, '
	SELECT SUBSTR(ADDDATE, 1, 8) AS 전송일,
			COUNT(*) AS 연동라인수, 
			SUM(CASE WHEN TRANSSTATE = ''Y'' THEN 1 ELSE 0 END) AS CJ확인,
			SUM(CASE WHEN TRANSSTATE = ''N'' THEN 1 ELSE 0 END) AS CJ미확인,
			SUM(CASE WHEN RSLTSTATE = ''Y'' THEN 1 ELSE 0 END) AS CJ출고,
			SUM(CASE WHEN READSTATE = ''Y'' THEN 1 ELSE 0 END) AS CLOUD전송,
			COUNT(CASE WHEN RSLTSTATE = ''Y'' AND SHIPQTY != ''0'' THEN 1 END) AS 매출,
			COUNT(CASE WHEN RSLTSTATE = ''Y'' AND SHIPQTY = ''0'' THEN 1 END) AS 결품,
			SUM(CASE WHEN RSLTSTATE = ''N'' THEN 1 ELSE 0 END) AS CJ미출고
	FROM P1_V_ORDERS
	GROUP BY SUBSTR(ADDDATE, 1, 8)
	ORDER BY SUBSTR(ADDDATE, 1, 8) DESC
')

---완성3!
SELECT * from openquery(CJ_3PL, '
	SELECT 
		CASE
			WHEN STR_EXT01 = ''Delivery01'' THEN ''CJ택배''
			WHEN STR_EXT01 = ''Delivery02'' THEN ''내일 꼭! 오네''
			WHEN STR_EXT01 = ''Delivery03'' THEN ''KEP수원''
			WHEN STR_EXT01 = ''Delivery04'' THEN ''LF DC1(직배송)''
			WHEN STR_EXT01 = ''Delivery05'' THEN ''SK기흥''
			WHEN STR_EXT01 = ''Delivery06'' THEN ''경동택배''
			WHEN STR_EXT01 = ''Delivery07'' THEN ''나비MRO(오산)''
			WHEN STR_EXT01 = ''Delivery08'' THEN ''로젠택배''
			WHEN STR_EXT01 = ''Delivery09'' THEN ''서브원산시배송''
			WHEN STR_EXT01 = ''Delivery10'' THEN ''서브원평택물류''
			WHEN STR_EXT01 = ''Delivery11'' THEN ''에버랜드배송''
			WHEN STR_EXT01 = ''Delivery12'' THEN ''직배''
			WHEN STR_EXT01 = ''Delivery13'' THEN ''직배(고객물류수령)''
			WHEN STR_EXT01 = ''Delivery14'' THEN ''직배(용차)''
			WHEN STR_EXT01 = ''Delivery15'' THEN ''천일택배''
			WHEN STR_EXT01 = ''Delivery16'' THEN ''한국니토옵티컬''
			WHEN STR_EXT01 = ''Delivery17'' THEN ''GS리테일''
			ELSE ''기타 배송사''
			END AS 배송사,
			COUNT(*) AS 연동라인수, 
			SUM(CASE WHEN TRANSSTATE = ''Y'' THEN 1 ELSE 0 END) AS CJ확인,
			SUM(CASE WHEN TRANSSTATE = ''N'' THEN 1 ELSE 0 END) AS CJ미확인,
			SUM(CASE WHEN RSLTSTATE = ''Y'' THEN 1 ELSE 0 END) AS CJ출고,
			SUM(CASE WHEN READSTATE = ''Y'' THEN 1 ELSE 0 END) AS CLOUD전송,
			SUM(CASE WHEN RSLTSTATE = ''N'' THEN 1 ELSE 0 END) AS CJ미출고,
			ROUND(SUM(CASE WHEN RSLTSTATE = ''Y'' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 1) AS 진척률
	FROM P1_V_ORDERS
	WHERE SUBSTR(ADDDATE, 1, 8) BETWEEN ''20241002'' AND ''20241002''
	GROUP BY STR_EXT01
	ORDER BY STR_EXT01
')


SELECT * from openquery(CJ_3PL, '
	SELECT 
    COALESCE(o.ORDERDATE, t.ORDERDATE) AS ORDERDATE,
    COALESCE(o.count, 0) AS P1_V_ORDERS_COUNT,
    COALESCE(t.count, 0) AS P1_V_ORDERS_TO_COUNT
FROM 
    (SELECT ORDERDATE, COUNT(*) AS count
     FROM P1_V_ORDERS
     GROUP BY ORDERDATE) T1
FULL OUTER JOIN 
    (SELECT ORDERDATE, COUNT(*) AS count
     FROM P1_V_ORDERS_TO
     GROUP BY ORDERDATE) t
ON o.ORDERDATE = t.ORDERDATE
ORDER BY ORDERDATE;
');



SELECT COUNT(*) from openquery(CJ_3PL,'select * from P1_V_ORDERS')
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS_TO')



SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS where ADDDATE LIKE ''20241008%''')

SELECT COUNT(*) from openquery(CJ_3PL,'select * from P1_V_ORDERS') WHERE RSLTSTATE='Y'

SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS where ADDDATE=''20240923162006''')
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS_TO where EXTERNORDERKEY=''P24O1551895B1''')

--SUBSTR(ORDERDATE,1,8) BETWEEN ''20240921'' AND ''20240928'' order by RSLTDATE desc ')


-- 운영버전
SELECT * from openquery(CJ_3PL,'select * from P1_V_SKU WHERE SKU = ''883814''')
SELECT * from openquery(CJ_3PL,'select * from P1_V_STORER2  WHERE CUST=''39005328''')

SELECT * from openquery(CJ_3PL,'select * from P1_V_RECEIPT') WHERE EXTERNORDERKEY='10030018408469'
SELECT * from openquery(CJ_3PL,'select * from P1_V_RECEIPT_TO') WHERE EXTERNORDERKEY='10030018408469'

SELECT * from openquery(CJ_3PL,'select * from P1_V_LOC')WHERE ADDDATE LIKE '20240912%' AND SKU='100220'

SELECT * from openquery(CJ_3PL,'select * from P1_V_LOC') WHERE SKU='100220' AND ADDDATE LIKE '20240827%'
SELECT * from openquery(CJ_3PL,'select * from P1_V_STORER2') WHERE CUSTTYPE='P' AND CUST LIKE '%TEST%'

---송장내품정보
SELECT * from openquery(CJ_3PL, 'select * from P1_V_SUBDIVISION') WHERE ADDDATE LIKE '20240920%' ORDER BY ADDDATE DESC

SELECT EXTERNORDERKEY from openquery(CJ_3PL,'select * from P1_V_ORDERS') WHERE TRANSSTATE='Y' GROUP BY EXTERNORDERKEY 
SELECT EXTERNORDERKEY from openquery(CJ_3PL,'select * from P1_V_ORDERS_TO') WHERE TRANSSTATE='Y' GROUP BY EXTERNORDERKEY 
WHERE RSLTDATE LIKE '20240723%'

SELECT * from openquery(CJ_3PL,'select * from P1_V_RECEIPT') WHERE EXTERNORDERKEY='10030018374287'
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS') WHERE STR_EXT03='0062' AND RSLTSTATE='N'

WHERE STR_EXT01='Delivery12' AND CUSTNAME LIKE '%농협경제%'

SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS') WHERE EXTERNORDERKEY='100300183696422'
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS_TO') WHERE EXTERNORDERKEY='100300183696422'




SELECT EXTERNORDERKEY, ADDDATE, ORDERDATE from openquery(CJ_3PL, 'select * from P1_V_ORDERS') WHERE ADDDATE LIKE '20240730%' GROUP BY EXTERNORDERKEY, ADDDATE, ORDERDATE ORDER BY ORDERDATE
WHERE ADDDATE LIKE '20240722%'
WHERE RSLTDATE LIKE '20240722%'

SELECT * from openquery(CJ_3PL, 'select * from P1_V_RETURN')WHERE EXTERNORDERKEY='10030018209044'

SELECT * from openquery(CJ_3PL,'select * from P1_V_PRINT') WHERE BARCODE_NO='HO20240719003002'

SELECT * from openquery(CJ_3PL,'select * from P1_V_RETURN') WHERE EXTERNORDERKEY='10030018246517'
SELECT * from openquery(CJ_3PL,'select * from P1_V_RETURN_TO') WHERE EXTERNORDERKEY='10030018246517'


---무재고 확인 (입고확정/출고확정) - 배송번호 기준
SELECT * from openquery(CJ_3PL,'select * from P1_V_RECEIPT_TO') WHERE STR_EXT05='10030018368923'
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS_TO') WHERE EXTERNORDERKEY='10030018368923'
---무재고 확인 (입고예정/입고확정/출고예정/출고확정) - 발주번호 기준
SELECT * from openquery(CJ_3PL,'select * from P1_V_RECEIPT') WHERE EXTERNORDERKEY='10030019011332'
SELECT * from openquery(CJ_3PL,'select * from P1_V_RECEIPT_TO') WHERE EXTERNORDERKEY='10030019011332'
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS') WHERE FILE_ID='13' AND STR_EXT04='10030018811406'
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS_TO') WHERE FILE_ID='13' AND STR_EXT04='10030018811406'


---무재고 입고(33)/출고(13) 예정정보 확인
SELECT * from openquery(CJ_3PL,'select * from P1_V_RECEIPT') WHERE FILE_ID='33'
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS') WHERE FILE_ID='13'


---발주관리 예정->확정
SELECT * from openquery(CJ_3PL,'select * from P1_V_RECEIPT') WHERE EXTERNORDERKEY='10030018545403'
SELECT * from openquery(CJ_3PL,'select * from P1_V_RECEIPT_TO') WHERE EXTERNORDERKEY='10030018545403'


---출고 예정->확정
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS where READSTATE=''N'' and RSLTSTATE=''Y''')
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS where READSTATE=''Y'' and RSLTSTATE=''N''')
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS_TO where READSTATE=''Y'' and RSLTSTATE=''N''')

SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS where EXTERNORDERKEY=''P24O1551895B1''')
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS_TO where EXTERNORDERKEY=''P24O1551895B1''')

SELECT * from openquery(CJ_3PL,'select * from P1_V_RECEIPT_TO where STR_EXT04=''P24O1551895B1''')


---반품 예정->확정
SELECT * from openquery(CJ_3PL,'select * from P1_V_RETURN') WHERE ADDDATE LIKE '202408%' AND EXTERNORDERKEY='S24O1417338R1'
SELECT * from openquery(CJ_3PL,'select * from P1_V_RETURN') WHERE EXTERNORDERKEY='10030019051677'
SELECT * from openquery(CJ_3PL,'select * from P1_V_RETURN_TO') WHERE EXTERNORDERKEY='10030019051677'


---출고정보의 라인수 확인용
SELECT COUNT(*) from openquery(CJ_3PL,'select * from P1_V_ORDERS') WHERE RSLTSTATE='Y'
SELECT COUNT(*) from openquery(CJ_3PL,'select * from P1_V_ORDERS_TO') WHERE RSLTSTATE='Y'


---아름넷이 읽어가지 않은 출고확정정보
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS_TO') WHERE RSLTSTATE='Y' AND READSTATE='N'


---부분출고 수량 누락건 확인용
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS_TO') WHERE SHIPQTY != 0 AND ORGQTY != SHIPQTY


---무재고 입고확정수량 != 출고확정수량 비교용 -> 만드는 중
SELECT * from openquery(CJ_3PL,'select * from P1_V_RECEIPT_TO') WHERE FILE_ID='33'
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS_TO') WHERE FILE_ID='13' AND ORGQTY != SHIPQTY ORDER BY RSLTDATE DESC
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS') WHERE EXTERNORDERKEY='P24O1391779B1'
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS_TO') WHERE EXTERNORDERKEY='P24O1391779B1'



---출고확정정보 최근 업데이트 일시/건수 확인용 - 전체
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS_TO') WHERE RSLTSTATE='Y' AND READSTATE='Y' AND RSLTDATE LIKE '20240809:11%' ORDER BY RSLTDATE DESC ---조회일 CJ 확정성공 & ODK연동성공
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS_TO') WHERE RSLTSTATE='Y' AND READSTATE='Y' AND READDATE LIKE '2024080911%' ORDER BY READDATE DESC ---조회일 CJ 확정성공 & ODK_READDATE기준
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS_TO') WHERE RSLTSTATE='Y' AND READSTATE!='Y' AND ORGQTY!=SHIPQTY ORDER BY RSLTDATE DESC ---890라인
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS_TO') WHERE RSLTSTATE='Y' AND ORGQTY!=SHIPQTY AND SHIPQTY!=0 ORDER BY RSLTDATE DESC ---25건
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS_TO') WHERE RSLTSTATE='Y' AND READSTATE!='Y' AND ORGQTY=SHIPQTY ORDER BY RSLTDATE DESC ---2888라인

SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS_TO') T1 WHERE T1.READDATE LIKE '2024080910%' ORDER BY T1.READDATE DESC

---출고확정정보 시간대별 라인수/건수 
SELECT SUBSTRING(READDATE, 1, 10) HOUR, COUNT(SUBSTRING(READDATE, 1, 10)) LINE, COUNT(DISTINCT ORDERKEY) PO
FROM openquery(CJ_3PL,'select * from P1_V_ORDERS_TO')
WHERE READDATE LIKE '20241017%'
GROUP BY SUBSTRING(READDATE, 1, 10)
ORDER BY HOUR


SELECT * from openquery(CJ_3PL,'
			SELECT SUBSTR(T1.RSLTDATE, 1, 11) ||''시 = 라인수 : ''|| COUNT(T1.EXTERNORDERKEY) ||'' , 건수 : ''|| COUNT(DISTINCT T1.EXTERNORDERKEY) AS strText
			  FROM P1_V_ORDERS_TO T1
			 WHERE T1.STORERKEY = ''P1'' and SUBSTR(T1.RSLTDATE, 1, 8) = TO_CHAR(SYSDATE-1, ''YYYYMMDD'')
			 and TO_CHAR(ADD_MONTHS(T1.RSLTDATE, 1), ''HH24'') = TO_CHAR(SYSDATE-1/24, ''HH24'')
			 GROUP BY SUBSTR(T1.RSLTDATE, 1, 11)
			 ORDER BY SUBSTR(T1.RSLTDATE, 1, 11) DESC')


SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS_TO') WHERE RSLTSTATE='Y' AND READSTATE='Y' AND RSLTDATE<'20240730100000' AND RSLTDATE>='20240730000000'
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS_TO') WHERE RSLTSTATE='Y' AND READSTATE='Y' AND RSLTDATE LIKE '20240730%' AND ORGQTY!=SHIPQTY ORDER BY RSLTDATE


---출고예정정보 일시/건수 확인용
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS') WHERE ADDDATE LIKE '20240806%'
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS') WHERE ADDDATE<'20240730100000' AND ADDDATE>='20240730000000'
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS') WHERE EXTERNORDERKEY='100300188144741'
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS_TO') WHERE EXTERNORDERKEY='100300188144741'


SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS') WHERE EXTERNORDERKEY='100300184406811'
select * from openquery(CJ_3PL, 'select *  FROM COLS') where TABLE_NAME='P1_V_ORDERS'
select * from openquery(CJ_3PL, 'select *  FROM COLS') where TABLE_NAME='P1_V_ORDERS_TO' order by column_id asc





P1_V_SKU		: 1. 상품정보[P1_V_SKU]
P1_V_STORER2	: 2-1. 거래처정보 (거래처타입 C : 일반거래처 일 경우)				
P1_V_STORER2	: 2-2. 거래처정보 (거래처타입 P : 매입업체 일 경우)				
P1_V_RECEIPT	: 3. 입고예정정보				
P1_V_RECEIPT_TO : 4. 입고확정정보			
P1_V_ORDERS		: 5. 출고예정정보 (주문구분 : B2B | B2C | 그 외 타입별로 클라우드 매핑 달라짐)				
P1_V_ORDERS_TO	: 6. 출고확정정보	
P1_V_RETURN		: 7. 반품예정정보 (B2B | B2C 등 주문유형 별 반품 프로세스 점검)				
P1_V_RETURN_TO	: 8. 반품확정정보	
P1_V_LOC		: 9. 재고정보 - CJ측 DB준비완, ARUM 확인필			
P1_V_SUBDIVISION : 11. 송장내품정보	
P1_V_PRINT : 13. 별도거래명세서고객정보
P1_V_PRINTITEM : 14. 별도거래명세서상품정보	



SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS_TO') WHERE RSLTSTATE='Y' AND READSTATE='N' AND RSLTDATE LIKE '20240731%' ORDER BY RSLTDATE DESC ---조회일 CJ 확정성공 & ODK연동성공
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS') WHERE ADDWHO='arumnet' AND SHIPTO='29005764' AND RSLTSTATE='Y' AND READSTATE='N' AND ORDERDATE!='20240731'
SELECT * from openquery(CJ_3PL,'select * from P1_V_ORDERS') WHERE EXTERNORDERKEY LIKE 'MRO240723398035%'


SELECT COUNT(*) from openquery(CJ_3PL,'select * from P1_V_ORDERS') WHERE ADDWHO='arumnet' AND RSLTSTATE='E' AND ORDERDATE!='20240731'

---ARUM DB
select top 100 * from OPENQUERY (ARUM_SALES, 'select * from SALE_INFO ORDER BY CREATE_DT DESC ')


select top 10000 * from OPENQUERY (ARUM_SALES, 'select * from SALE_INFO')

select * from OPENQUERY (ARUM_SALES, 'select * from SALE_INFO') WHERE INV_NO='1302061030K6X20535'


